replicaCount: 3

image:
  repository: blog-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

