replicaCount: 3

image:
  repository: jaayshaun/blog-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: true
  name: ""


livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 30
  timeoutSeconds: 5

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podSecurityContext: {}
securityContext: {}

imagePullSecrets: []
nodeSelector: {}
affinity: {}
tolerations: []

