apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blog-app-chart.serviceAccountName" . }}
  labels:
    {{- include "blog-app-chart.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}

